/**
 * generate.c
 *
 * Computer Science 50
 * Problem Set 3
 *
 * Generates pseudorandom numbers in [0,LIMIT), one per line.
 *
 * Usage: generate n [s]
 *
 * where n is number of pseudorandom numbers to print
 * and s is an optional seed
 */
       
#include <cs50.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define LIMIT 65536

int main(int argc, string argv[])
{
    // Verify that command line arguments have been supplied.
    // - argc will always at least equal 1 (the program name typed on the command line.)
    // - argc[1] : number of pseudorandom numbers to generate.
    // - argc[2] : number to use to set the seed for rand. 
    if (argc != 2 && argc != 3)
    {
        printf("Usage: ./generate n [s]\n");
        return 1;
    }

    // convert the first command line argument from a string to an int.
    // - argv[1]: the amount of random numbers to generate.
    int n = atoi(argv[1]);

    // Call srand to set the initial seed for rand.
    // Otherwise use the current time as the seed.
    // - srand can affect how rand is being 'seeded' because they
    //   both share the same global variable.
    // - http://stackoverflow.com/questions/21273550/
    if (argc == 3)
    {
        srand((unsigned int) atoi(argv[2]));
    }
    else
    {
        srand((unsigned int) time(NULL));
    }

    // Print out n amount random numbers generated by rand.
    for (int i = 0; i < n; i++)
    {
        printf("%i\n", rand() % LIMIT);
    }

    // that's all folks
    return 0;
}
